# Generated by Django 5.1.4 on 2025-02-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='photo',
            field=models.ImageField(default=False, upload_to='photos/%y/%m/%d/'),
            preserve_default=False,
        ),
    ]
