# Generated by Django 5.1.4 on 2025-03-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(default='Open'),
        ),
    ]
