# Generated by Django 5.1.4 on 2025-03-04 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_event_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Category',
            new_name='category',
        ),
    ]
