# Generated by Django 5.1.4 on 2025-03-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_rename_category_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
