# Generated by Django 5.1.4 on 2025-02-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('photo_location', models.ImageField(upload_to='stades/%y/%m/%d/')),
                ('status', models.CharField(max_length=100)),
                ('nbr_places', models.CharField(max_length=100)),
            ],
        ),
    ]
