# Generated by Django 5.1.4 on 2025-05-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0002_ticket_cost_price_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='cost_price',
            field=models.FloatField(default=0),
        ),
    ]
