# Generated by Django 5.1.4 on 2025-05-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0003_alter_ticket_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='etickets_count',
            field=models.IntegerField(default=0),
        ),
    ]
